<?php

/**
 * php-cs-fixer configuration used to validate the PHP code generated by
 * this renderer (the e2e fixture outputs), the e2e smoke test, the
 * conformance runner and the phpunit coverage suite.
 *
 * Ruleset: PER-CS 2.0 (superset of PSR-12) + enforced strict_types.
 */

declare(strict_types=1);

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__ . '/e2e')
    ->path('/generated\//')
    ->append([
        __DIR__ . '/e2e/smoke.php',
        __DIR__ . '/e2e/conformance_runner.php',
        __DIR__ . '/e2e/phpunit/ConformanceTest.php',
        __DIR__ . '/e2e/phpunit/RuntimeCoverageTest.php',
        __DIR__ . '/tools/check-coverage.php',
    ]);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setUnsupportedPhpVersionAllowed(true)
    ->setRules([
        '@PER-CS2.0' => true,
        'declare_strict_types' => true,
    ])
    ->setUsingCache(false)
    ->setFinder($finder);
